CREATE ROLE sensoric WITH LOGIN PASSWORD '*********';
CREATE DATABASE sensoric;

#\c sensoric

CREATE TABLE sensors (
    id UUID PRIMARY KEY,
    serial_number VARCHAR(128) NOT NULL UNIQUE,
    name VARCHAR(64) NOT NULL
);

GRANT SELECT, UPDATE, DELETE, INSERT ON ALL TABLES IN SCHEMA public TO sensoric;
